### ISSUE TITLE
Support Locale for date parsing in sprintf format

### ISSUE THREAD

**Issue by dadoonet** [elasticsearch/logstash#2315]
When parsing a date with `sprintf`, we use by default the local `Locale`.

For example:

```
 mutate {
    replace => { "message" => "%{start}[%{+dd/MMM/YYYY:HH:mm:ss Z}]%{end}" }
  }
```

could produce something different when running on a french computer than on an english computer: `14/déc./2014:00:13:42 +0000` vs `14/Dec/2014:00:13:42 +0000`.

It could be nice to specify for a date the Locale we want to use whatever is set on the computer.

`%{+LOCALE@DATE_FORMAT}` such as:

```
 mutate {
    replace => { "message" => "%{start}[%{+fr@dd/MMM/YYYY:HH:mm:ss Z}]%{end}" }
  }
```

**Comment by wiibaa** [comment]
Hi @dadoonet, sorry to highjack your issue but I would like to include in this issue discussion the following points to get your advice and the team point of view:

* possibility to configure the timezone as discussed in https://logstash.jira.com/browse/LOGSTASH-520
* possibility to apply this date formatting to others fields than @timestamp

My last idea would be to introduce in the syntax the notion of **filter** using `|` (stolen idea from AngularJs)

Following your example, here would be the full syntax to apply a `date` filter to the @timestamp field
````
mutate {
    replace => { "message" => "%{start}[%{@timestamp | date(:locale => 'fr', :pattern => 'dd/MMM/YYYY:HH:mm:ss Z', :timezone => 'Europe/Paris')}]%{end}" }
  }
````
But the shortcut `%{+` syntax could be kept and even augmented with the locale as you propose but I have doubt about adding the timezone.
Thoughts ?

**Comment by untergeek** [comment]
@dadoonet doesn't the [locale](http://www.elasticsearch.org/guide/en/logstash/current/plugins-filters-date.html#plugins-filters-date-locale) option in the date filter cover this already?

In any case, 
Let's migrate this discussion to https://github.com/logstash-plugins/logstash-filter-date/issues/10

**Comment by wiibaa** [comment]
@untergeek the concern is the **event.sprintf()** not really the date filter as logstash enforce the @timestamp to be stored in UTC

**Comment by jordansissel** [comment]
@untergeek yeah the original discussion I had with @dadoonet was a desire to have `%{+...}` allow requesting the format be done in another locale (French, etc)

**Comment by untergeek** [comment]
well, couldn't the locale field still be used for that in a configurable output?

**Comment by untergeek** [comment]
I will leave this open, but I think that it should be resolved in the date filter with alternate outputs (use that field) rather than an sprintf format change, though the latter sounds useful in other cases.

**Comment by jordansissel** [comment]
@untergeek this is unrelated to the date filter and has to do with the `@timestamp` field. The `%{+...}` syntax doesn't use the date filter.

For example, if I want to output my logs to "logstash-janvier" (janvier == january in french), I cannot do this today without irritation. A user may have htis configuration:

```
output {
  elasticsearch {
    index => "logstash-%{+MMMM}"
  }
}
```

But we cannot select the locale when doing time sprintf'ing, so this becomes nearly impossible for most users to accomplish.

To achieve this in jruby:
```
# pattern  is "logstash-MMMM" and I want french!
>> org.joda.time.DateTime.now.toString(org.joda.time.format.DateTimeFormat.forPattern("'logstash-'MMMM").withLocale(java.util.Locale::FRENCH))
=> "logstash-février"
```

Perfect and totally easy to do.

The proposal is to add a prefix to the time format for `%{+...}` time formatting which allows you to declare the locale, such as `%{+locale@time_format}`. Continuing from my example above, we could permit `logstash-%{+fr@MMMM}` which would request `MMMM` in french.

**Comment by jordansissel** [comment]
A similar request is likely desired for customizing the timezone as well as the locale, where I can ask for a time in Newfoundland's timezone, or Japan, or whatever.

**Comment by wiibaa** [comment]
With more thinking, I have finally reached @untergeek viewpoint that this behaviour should be in a filter instead of sprintf, but still not in the date filter. I would go for a new filter **date_formatter** as the current date filter is focused on **parsing** because IMHO it would be difficult and confusing to harmonize this two use cases in a unique filter. For example comparing the source/target:

Config parameter | Date parsing | Date formatting
---------------------- | ---------------- | -------------------
Source | Must be a string or an integer | Must be a time object
Target | **Time** object Default to @timestamp | **String** value Any field **EXCEPTED** @timestamp 

Thoughts ?

**Comment by wiibaa** [comment]
Just to make the discussion a little more concrete, here is a first stab https://github.com/wiibaa/logstash-filter-date_formatter
